# app config
spring:
  application:
    name: products-service
  # datasource config
  datasource:
    url: jdbc:mysql://localhost:3306/products_service_mdb
    username: root
    password: root
  # ddl config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# port config
server:
  port: 5004
  servlet:
    context-path: /products-service

# eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/